### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by alessio** [progrium/pluginhook#13]
Hi,

While I've been working on the Debian's packaging for pluginhook I noticed that, although the README.md file mentions MIT as the license under which the sources are distributed, the sources lack a proper LICENSE or COPYING file.
 
Could you please add such file to clarify the license terms?

Thanks for considering.

**Comment by alessio** [comment]
BTW, this is the Debian's Intent To Package bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=778484

I'll upload it as soon as this issue is fixed.

**Comment by progrium** [comment]
added
